version: "3.8"

services:
  postgres-db:
    image: postgres:latest
    container_name: db_app
    env_file:
      - .env-non-dev
    ports:
      - "5432:5432"

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - "9000:8000"
    depends_on:
      - postgres-db
