version: "2.22.0"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 5432
    expose:
      - 2345
    env_file:
      - .env-non-dev

  app:
    build:
      context: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["/fastapi_app/docker/app.sh"]
    ports:
      - 6789:8000
    depends_on:
      - db
